defaults: &defaults
  working_directory: ~/project
  docker: [ image: 'nfour/circleci-node:9' ]

restoreCache: &restoreCache
  restore_cache:
    keys:
      - deps-{{ checksum "package.json" }}
      - deps-
      - build-{{ .Environment.CIRCLE_SHA1 }}

attachWorkspace: &attachWorkspace
  attach_workspace:
    at: '/tmp/workspace'

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - run: yarn install
      - save_cache:
          paths: [node_modules]
          key: deps-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: '/tmp/workspace'
          paths: [build]

  lintTest:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - *attachWorkspace
      - run: yarn lint

  unitTest:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - *attachWorkspace
      - run: yarn test:coverage

  changelogTest:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - *attachWorkspace
      - run: yarn changelog:verify

  deploy:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - *attachWorkspace
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: ls -lsah && yarn release

tagFilters: &tagFilters
  filters: { tags: { only: /.*/ } }

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          <<: *tagFilters

      - lintTest:
          <<: *tagFilters
          requires: [build]

      - unitTest:
          <<: *tagFilters
          requires: [build]

      - changelogTest:
          <<: *tagFilters
          requires: [build]

      - deploy:
          requires: [build, lintTest, unitTest, changelogTest]
          filters:
            tags: { only: /^v.*/ }
            branches: { ignore: /.*/ }

