defaults: &defaults
  working_directory: ~/project
  docker: [ image: 'nfour/circleci-node:9' ]

restoreCache: &restoreCache
  restore_cache:
    keys:
    - dependencies-{{ checksum "package.json" }}
    - dependencies-

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - run: yarn install

      - save_cache:
          paths: [node_modules]
          key: dependencies-{{ checksum "package.json" }}

  lintTest:
    <<: *defaults

    steps:
      - *restoreCache
      - run: "yarn lint"

  unitTest:
    <<: *defaults

    steps: [ run: "yarn test:coverage" ]

  changelogTest:
    <<: *defaults

    steps: [ run: "yarn changelog:verify" ]

  deploy:
    <<: *defaults

    steps: [ run: "yarn release" ]


workflows:
  version: 2
  deploy:
    jobs:
      - build
      - lintTest: { requires: [build] }
      - unitTest: { requires: [build] }
      - changelogTest: { requires: [build] }
      - deploy:
          requires: [build, lintTest, unitTest, changelogTest]
          filters:
            tags: { only: /^v\b.+/ }


